### ISSUE TITLE
Bug Report: Game Crashing When Fixes Are Applied

### ISSUE THREAD

**Issue by owendeveloper490** [TheRealJake12/Smoke--Em-Out-Struggle-Kade-Engine#1]
whenever i followed the steps to fix the game so that this could work it didn't work
help

**Comment by TheRealJake12** [comment]
can you undo them. they arent required. just there if it breaks

**Comment by owendeveloper490** [comment]
@TheRealJake12 let me try it again, because if i try to do it without the linc_luajit fix then it won't compile

**Comment by owendeveloper490** [comment]
it works now
