### ISSUE TITLE
Question: How To Add BG's to KE 1.7

### ISSUE THREAD

**Issue by GithubSquare322** [TheRealJake12/Smoke--Em-Out-Struggle-Kade-Engine#2]
how did u add the garcello background into kade engine 1.7? i'm porting a mod to kade engine but i can't find the code to add the background...

**Comment by TheRealJake12** [comment]
> how did u add the garcello background into kade engine 1.7? i'm porting a mod to kade engine but i can't find the code to add the background...

look in the stage.hx code and basically copy what I have done in garAlley statement
